[project]
name = "aind-vr-foraging-primary-data-aggregator"
version = "42.42.42"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "aind-behavior-vr-foraging-packaging==0.0.19",
    "aind-data-access-api>=1.10.0",
    "aind-data-schema>=2.9.0",
    "packaging>=26.3",
    "ruff>=0.16.7",
    "s3fs>=2026.7.0",
]
